# Imagen oficial de Node optimizada
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia solo package.json y package-lock.json primero para cachear dependencias
COPY package*.json ./

# Instala dependencias (usa --production si solo quieres las de prod)
RUN npm install

# Copia el resto del código de tu backend al contenedor
COPY . .

# Puerto expuesto
EXPOSE 9000

# Arranca la app
CMD ["npm", "start"]
